name: CI
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    # pipe-failなどを有効にするために指定
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Initialize Supabase
        id: supabase
        run: |
          supabase start
          supabase status -o env >> $GITHUB_OUTPUT
      - name: Create dot env for ci
        run: |
          echo "SUPABASE_URL=${{ steps.supabase.outputs.API_URL }}" > .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ steps.supabase.outputs.SERVICE_ROLE_KEY }}" >> .env
      - name: Run DB Lint
        run: supabase db lint
      - name: Run tests
        run: npm test
