name: Terraform Lint

on:
  pull_request:
    paths:
      - 'terraform/**'
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # Terraform CLIをセットアップ
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Terraformフォーマットチェック
      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: ./terraform

      # Terraform Lintチェック
      - name: Terraform Lint Check
        run: terraform validate
        working-directory: ./terraform
